name: rayosbinder
channels:
  - anaconda
  - conda-forge
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - attrs
  - backcall
  - blas
  - bleach
  - blosc
  - brotli
  - brotli-bin
  - bzip2
  - certifi
  - charls
  - cloudpickle
  - colorama
  - cycler
  - cytoolz
  - dask-core
  - decorator
  - defusedxml
  - entrypoints
  - freetype
  - future
  - giflib
  - imagecodecs
  - imageio
  - importlib-metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab_widgets
  - jxrlib=1.1
  - kiwisolver
  - lcms2=2.12
  - lerc=2.2.1
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - liblapack
  - libpng
  - libsodium
  - libtiff
  - libwebp-base
  - libzopfli
  - lz4-c
  - markupsafe=2.0.1
  - matplotlib-base
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - networkx
  - notebook
  - numpy
  - numpy-base
  - olefile
  - openjpeg
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pickleshare
  - pillow
  - pip
  - prometheus_client
  - prompt-toolkit
  - pydicom
  - pygments
  - pyparsing
  - pyrsistent
  - python
  - python-dateutil
  - python-highcharts
  - python_abi
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - scikit-image
  - scipy
  - send2trash
  - setuptools
  - six
  - snappy
  - terminado
  - testpath
  - tifffile
  - tk
  - toolz
  - tornado
  - traitlets
  - typing_extensions
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - yaml
  - zeromq
  - zfp
  - zipp
  - zlib
  - zstd
