name: rayos
channels:
  - anaconda
  - conda-forge
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - aiohttp
  - argon2-cffi
  - async-timeout
  - async_generator
  - attrs
  - backcall
  - bleach
  - blinker
  - brotlipy
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - colorama
  - cryptography
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core
  - decorator
  - defusedxml
  - entrypoints
  - freetype
  - future
  - gdcm
  - glob2
  - google-auth
  - google-auth-oauthlib
  - gspread
  - httplib2
  - icu
  - idna
  - idna_ssl
  - imageio
  - importlib-metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab_pygments
  - jupyterlab_widgets
  - kiwisolver
  - lcms2
  - libblas
  - libcblas
  - libclang
  - liblapack
  - libpng
  - libsodium
  - libtiff
  - lz4-c
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune=0.8.4
  - mkl=2020.4
  - msys2-conda-epoch
  - multidict
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - notebook
  - numpy=1.19.5
  - oauth2client
  - oauthlib
  - olefile
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pickleshare
  - pillow
  - pip
  - pivottablejs
  - prometheus_client
  - prompt-toolkit
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pydicom
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-highcharts
  - python_abi
  - pytz
  - pywavelets
  - pywin32
  - pywinpty
  - pyyaml
  - pyzmq
  - qt
  - requests
  - requests-oauthlib
  - rsa
  - scikit-image
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - six=1.15.0
  - sqlite
  - tabulate
  - terminado
  - testpath
  - threadpoolctl
  - tk
  - toolz
  - tornado
  - traitlets
  - typing-extensions
  - typing_extensions
  - urllib3
  - vc
  - vs2015_runtime
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - win_inet_pton
  - wincertstore
  - winpty
  - xz
  - yaml
  - yapf
  - yarl
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - pymupdf
